plugins {
    id 'java'
    id 'maven-publish'
    id("io.papermc.paperweight.userdev") version '2.0.0-beta.21'
}

group = 'io.rivrs'
version = "1.0"

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven { url = uri("https://repo.codemc.io/repository/maven-releases/") }
    maven { url = uri("https://repo.codemc.io/repository/maven-snapshots/") }
}

dependencies {
    paperweight.paperDevBundle("26.1.2.build.72-stable")
    compileOnly("com.github.retrooper:packetevents-spigot:2.13.0")

    compileOnly 'org.projectlombok:lombok:1.+'
    annotationProcessor 'org.projectlombok:lombok:1.+'
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    eachFile { details ->
        if (details.name.contentEquals('plugin.yml') || details.name.contentEquals('bungee.yml')) {
            filter { String line ->
                line.replace('${project.version}', version)
            }
        }
    }
}


publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "astralrealms"
            url = version.toString().endsWith("SNAPSHOT")
                    ? "https://maven.astralrealms.fr/repository/maven-snapshots/"
                    : "https://maven.astralrealms.fr/repository/maven-releases/"
            credentials(PasswordCredentials)
        }
    }
}
