name: LibBL
version: ${project.version}
main: io.rivrs.libbl.LibBL
api-version: '26.1'
load: STARTUP
authors: [ Reytz, LordKiwix ]
depend:
  - packetevents
permissions:
  libbl.schematic:
    description: Paste a schematic as fake blocks with /fakeschem
    default: op
